/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "oyademtcgargifvvrslj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95YWRlbXRjZ2FyZ2lmdnZyc2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzOTI4NzYsImV4cCI6MjA3ODk2ODg3Nn0.XHTbtDo4X-hI9h-WPwFX_9NcvxuN2y0tZRtP0mpuc6E"